USE [master]
GO

/****** Object:  Database [TimsTool]    Script Date: 22/12/2022 16:31:34 ******/
DROP DATABASE [TimsTool]
GO

/****** Object:  Database [TimsTool]    Script Date: 22/12/2022 16:31:34 ******/
CREATE DATABASE [TimsTool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimsTool', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TimsTool.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimsTool_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TimsTool_log.ldf' , SIZE = 335872KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimsTool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimsTool] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimsTool] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimsTool] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimsTool] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimsTool] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimsTool] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimsTool] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimsTool] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimsTool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimsTool] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimsTool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimsTool] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimsTool] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimsTool] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimsTool] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimsTool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimsTool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimsTool] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimsTool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimsTool] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimsTool] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimsTool] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimsTool] SET RECOVERY FULL 
GO

ALTER DATABASE [TimsTool] SET  MULTI_USER 
GO

ALTER DATABASE [TimsTool] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimsTool] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimsTool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimsTool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimsTool] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimsTool] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TimsTool] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TimsTool] SET  READ_WRITE 
GO

